# Workflow is based on the Astropy GitHub actions workflow, ci_workflows.yml
name: CI

on:
    push:
        branches:
            - '*'
        tags:
            - '*'
    pull_request:

# 2025-01-07
# NERSC has Python 3.10, Numpy 1.22.4, Scipy 1.8.1, matplotlib 3.8.4, astropy 6.0.1, healpy 1.16.6, PyYAML 6.0.1
# PyPI has Python 3.13, Numpy 2.2.1, Scipy 1.15.0, matplotlib 3.10.0, astropy 7.0.0, healpy 1.18.0, PyYAML 6.0.2
# Numpy 1.26.4 was the last pre-2.0 Numpy.
#
jobs:
    tests:
        name: Unit tests
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                include:
                    - os: ubuntu-latest
                      python-version: '3.13'
                      numpy-version: '<3'
                      scipy-version: ''
                      astropy-version: '<89'
                    - os: ubuntu-latest
                      python-version: '3.12'
                      numpy-version: '<2.3'
                      scipy-version: '<2'
                      astropy-version: '<7.1'
                    - os: ubuntu-latest
                      python-version: '3.11'
                      numpy-version: '<2.1'
                      scipy-version: '<2'
                      astropy-version: '<7'
                    # Similar to NERSC but with last NumPy < 2.
                    - os: ubuntu-latest
                      python-version: '3.10'
                      numpy-version: '<2'
                      scipy-version: '<1.9'
                      astropy-version: '<6.1'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install Python dependencies
              run: |
                python -m pip install --upgrade 'pip<25' setuptools wheel
                python -m pip install pytest
                python -m pip install -r requirements.txt
                python -m pip install --upgrade --upgrade-strategy only-if-needed "numpy${{ matrix.numpy-version }}"
                python -m pip install --upgrade --upgrade-strategy only-if-needed "scipy${{ matrix.scipy-version }}"
                python -m pip install --upgrade --upgrade-strategy only-if-needed "astropy${{ matrix.astropy-version }}"
                python -m pip install .
            - name: Run the test
              run: pytest
